function [] = plot_digit(x, ncol, nrow)
%   plot the digits as images
%   By tianran Zhang

if nargin < 3
    [~, k] = size(x);
    ncol = 2;
    nrow = k/ncol;
end
figure;
imagesc(...
    cell2mat(...
        squeeze(...
            num2cell(...
                    reshape(x, [16, 16, ncol, nrow]), ...                    
                [1,2])...
            )...
        )...
    );
colormap gray;
end